Draft: GDB-9211: Add Pop-Up Menus for JSON-LD Export Selection
Ontotext-AD/graphdb-workbench pull request #1183
Opened 2024-01-08 17:04 UTC by VPetrova00

### **What**
New JSONLD export settings view

### **Why**
In order to export repository in JSONLD format with additional settings.

### **How**
Created a modal for new settings.
Created a new controller for additional settings view.
Created an export service.
Added translations to locale-en.json.

2024-01-08 17:07 UTC, VPetrova00 commented
What remains to be done:
- a cypress test
- translations in French
- fix an errors with the http get request

2024-01-11 14:05 UTC, VPetrova00 commented
> What remains to be done:
> 
> * a cypress test
> * translations in French
> * fix an errors with the http get request

Everything is addressed.

2024-01-15 12:40 UTC, svilenvelikov requested changes

2024-01-15 12:40 UTC, svilenvelikov commented on src/js/angular/import/templates/exportSettingsModal.html
> +            <div class="form-group row" ng-if="currentMode.name == 'framed' || currentMode.name == 'frame'">
You have already defined the JSONLDModesNames model which should be the source of truth and yet here you hardcode these types. Why? And something more. comparison in javascript must be done always by `===` or `!==`. There should be a really special case in order to use `==`.
So you can extract the names in a enum like object like this
``` javascript
$scope.JSONLDModesNames = $scope.JSONLDModes.reduce(function (acc, cur) {
   acc[cur.name] = cur.name;
   return acc;
}, {});
```
and then check against it here
```
 ng-if="currentMode.name === JSONLDModesNames.framed || currentMode.name == JSONLDModesNames.frame"
```
It'd be even better if we can omit these ^ checks here by having two lists with the repective types like 
```
$scope.JSONLDFramedModes = [JSONLDModesNames.framed, JSONLDModesNames.frame];
$scope.JSONLDContextModes = [JSONLDModesNames.context, JSONLDModesNames.compacted, JSONLDModesNames.flattened];
```
and then here you can just do
```
ng-if="JSONLDFramedModes.indexOf(currentMode.name) > -1"
```

2024-01-15 12:40 UTC, svilenvelikov commented on src/js/angular/rest/export.rest.service.js
> +        }
There is quite a lot of repetition here. Can you try to simplify this by extracting the url base which is repeated in all branches and then just add on top of it the other parameters.

2024-01-15 12:40 UTC, svilenvelikov commented on src/js/angular/rest/export.rest.service.js
> +        }, {timeout: 100}).then(function (res) {
Why this timeout was needed?

2024-01-15 12:40 UTC, svilenvelikov commented on src/js/angular/rest/export.rest.service.js
> +    function getExportedStatementsAsJSONLD(context, repo, graphsByValue, acceptHeader, linkHeader, auth, forSelectedGraphs) {
Document and reorder these parameters a bit. It'd have been better if they were fewer but still.

2024-01-17 09:18 UTC, VPetrova00 commented
Jenkins retry build

2024-01-19 08:41 UTC, VPetrova00 commented
Jenkins retry build

2024-01-19 09:31 UTC, svilenvelikov approved these changes

2024-01-19 09:32 UTC, merged