GDB-11134 fix error handling in my settings view
Ontotext-AD/graphdb-workbench pull request #1676
Opened 2024-11-01 15:59 UTC by svilenvelikov

## What
Fix the error handling in my settings view so that the UI state to be properly saved or retained when server error occurs during save or update operation.

## Why
This broken error handling harms the user experience in the view.

## How
* Extracted the ChangeUserPasswordSettingsCtrl as UserSettingsController in separate controller file. Extracted constants and utilities in separate files.
* Fixed saving user settings to happen in proper time.

## Testing

## Checklist
- [ ] Branch name
- [ ] Target branch
- [ ] Commit messages
- [ ] MR name
- [ ] MR Description
- [ ] Tests

2024-11-07 13:21 UTC, teodossidossev requested changes

2024-11-07 13:21 UTC, teodossidossev commented on src/js/angular/security/controllers/user-settings.controller.js
> +    $scope.getPrincipal = function () {
you can simply combine this and next methods. Looks odd as is

2024-11-07 13:21 UTC, teodossidossev commented on src/js/angular/security/controllers/user-settings.controller.js
> +        scope.user = {username: scope.userData.username};
we should introduce an UI user model

2024-11-07 16:35 UTC, svilenvelikov commented on src/js/angular/security/controllers/user-settings.controller.js
> +        scope.user = {username: scope.userData.username};
Sure. But not now.

2024-11-08 06:59 UTC, teodossidossev approved these changes

2024-11-08 07:03 UTC, merged