GDB-5416 Added logic, which saves previously selected option from search box into local storage and selects it on reopening the latter. Also added scroll to that element.
Ontotext-AD/graphdb-workbench pull request #409
Opened 2021-03-04 07:06 UTC by sava-savov-ontotext

2021-03-06 14:50 UTC, desislava-hristova-ontotext approved these changes

2021-03-07 20:51 UTC, yordanalexandrov requested changes

2021-03-07 20:51 UTC, yordanalexandrov commented on src/js/angular/core/templates/search-resource-input.html
>           ng-click="searchRdfResourceByEvent(autoCompleteUriResult, $event)" ng-class="{active: activeSearchElm === $index}"
I don't like this approach. You are using the hover styling to show that you have selected an element.
Those are two different indications. When you move the mouse, you don't know anymore what was selected.
You should just use another property to store the selected element's index and add another conditional class to the `auto-complete-results-wrapper` elements.
```
ng-class="{active: activeSearchElm === $index, selected: selectedElementIndex === $index}"
```

2021-03-08 09:29 UTC, yordanalexandrov approved these changes

2021-03-08 09:29 UTC, yordanalexandrov commented
LGTM

2021-03-08 09:46 UTC, merged