GDB-5525 Moved keyboard shortcuts button into SPARQL Editor
Ontotext-AD/graphdb-workbench pull request #410
Opened 2021-03-04 12:50 UTC by sava-savov-ontotext

2021-03-06 14:45 UTC, desislava-hristova-ontotext requested changes

2021-03-06 14:45 UTC, desislava-hristova-ontotext commented on src/css/lib/yasqe.min.css
> +    height: 300px;
This css comes from the yasqe library, right? In this case it is better to not modify it, but introduce the styling through our styles, in the case through new-sparql.css. Please, move all yasqe style changes there.

2021-03-08 11:29 UTC, sava-savov-ontotext commented
Jenkins retry build

2021-03-08 11:48 UTC, desislava-hristova-ontotext approved these changes

2021-03-09 07:05 UTC, sava-savov-ontotext commented
Jenkins retry build

2021-03-09 07:23 UTC, merged