GDB-6068 Implemented view for Smart Updates.
Ontotext-AD/graphdb-workbench pull request #493
Opened 2021-08-26 13:39 UTC by sava-savov-ontotext

The user will be able to see the list of already created templates, to edit and delete them, or create new template.

2021-09-13 12:59 UTC, desislava-hristova-ontotext requested changes

2021-09-13 12:59 UTC, desislava-hristova-ontotext commented on src/js/angular/sparql-template/controllers.js
> +        query: 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n' +
The default query should be something more generic like:
`PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.com#>
DELETE {
    ?subject ex:myPredicate ?oldValue .
} INSERT {
    ?subject ex:myPredicate ?newValue .
} WHERE {
    ?id rdf:type ex:MyType .
    ?subject ex:isRelatedTo ?id .
}`

2021-09-13 12:59 UTC, desislava-hristova-ontotext commented on src/js/lib/angularjs/1.3.8/angular.js
> - *   <script type="text/ng-template" id="templateId.html">
You should not modify the angular.js file.

2021-09-13 12:59 UTC, desislava-hristova-ontotext commented on src/js/angular/sparql-template/controllers.js
> +        if ($repositories.getActiveRepository() && !$repositories.isActiveRepoOntopType()) {
What about FedX repos? I guess it should not be supported also.

2021-09-20 10:24 UTC, sava-savov-ontotext commented
Jenkins retry build

2021-09-20 11:49 UTC, desislava-hristova-ontotext approved these changes

2021-09-20 11:49 UTC, merged