GDB-6448 Warn users when they unset the password
Ontotext-AD/graphdb-workbench pull request #538
Opened 2021-12-29 09:51 UTC by IvanovaD

A modal window is shown when the user clicks Save at "My settings" if he had checked Unset password checkbox. The modal warns the user about the consequences of unsetting the password.

2021-12-29 11:00 UTC, IvanovaD commented
Jenkins retry build

2021-12-29 12:34 UTC, IvanovaD commented
Jenkins retry build

2022-01-04 14:18 UTC, desislava-hristova-ontotext requested changes

2022-01-04 14:18 UTC, desislava-hristova-ontotext commented on src/js/angular/security/controllers.js
> +            if ($scope.noPassword) {
The warning should be present only when you unset password for users which has admin role.

2022-01-05 08:50 UTC, desislava-hristova-ontotext approved these changes

2022-01-05 08:50 UTC, merged