Gdb 6493 as a user i need to use remote location only to manage external graph db
Ontotext-AD/graphdb-workbench pull request #624
Opened 2022-04-19 11:33 UTC by sava-savov-ontotext

2022-04-20 07:53 UTC, yordanalexandrov requested changes

2022-04-20 07:53 UTC, yordanalexandrov commented on src/js/angular/core/services/repositories.service.js
> +                                    mapValues(result.data, (value, key) => {
You can use `Object.entries(result.data).forEach((key, value) => {...})` here, as you don't use the result from the `mapValues` fn.

2022-04-20 07:53 UTC, yordanalexandrov commented on src/js/angular/core/services/repositories.service.js
> +                    console.log('in error')
Remove this console logging

2022-04-20 07:53 UTC, yordanalexandrov commented on src/js/angular/repositories/fedx-repo.directive.js
> +                    mapValues(response, (value) => {
Perhaps use `forEach` here also, if not using the result from `mapValues`

2022-04-20 07:53 UTC, yordanalexandrov commented on src/js/angular/security/templates/user.html
> +								<tr ng-repeat="repository in getReadableRepositories() | orderBy: ['id', 'location']">
Would it not be better to have the repos sorted by location first and then id, so they are kind of grouped by location?

2022-04-20 07:53 UTC, yordanalexandrov commented on src/js/angular/security/controllers.js
> +                || repository.id !== SYSTEM_REPO && repository !== '*' && $scope.grantedAuthorities.READ_REPO['*']
`repository !== '*'` is not correct. I think it should be `repository.id !== '*'`. Can you double-check this. Same in below function on line 393.

2022-04-20 07:53 UTC, yordanalexandrov commented on src/template.html
> +                <li ng-repeat="repository in getReadableRepositories() | orderBy: ['type === \'system\'', 'id', 'location']"
Here also I think it will be better to sort by location first and then by id. Perhaps also show the local repos first.

2022-04-20 07:53 UTC, yordanalexandrov commented on src/pages/repository.html
> +                                Location
I18N the string

2022-04-20 07:53 UTC, yordanalexandrov commented on src/pages/repository.html
> +                                        ng-options="location.uri as location.label for location in locations">
Can the locations be sorted here also? Show local on top and then the rest?

2022-04-20 07:53 UTC, yordanalexandrov commented on src/pages/repositories.html
> +                                    ng-repeat="repository in getRepositoriesFromLocation(location.uri) | orderBy: ['type === \'system\'', 'id', 'location']"
Order by location is not needed here as the repositories are all from one location.

2022-05-11 07:16 UTC, yordanalexandrov approved these changes
lgtm

2022-05-11 07:29 UTC, svilenvelikov commented
It'll be good if we try to clear at least some of the sonar issues in order to improve the overall code quality.

2022-05-11 07:50 UTC, merged