GDB-7279 See the product capabilities in wb
Ontotext-AD/graphdb-workbench pull request #730
Opened 2022-09-16 07:53 UTC by Emskiqq

Add capabilities information to home page, license info page and upon registration page. 
Change graphDB version to 10.0.3-TR2 from 10.1.0-BOOTSTRAP-FTS-1.

2022-09-16 14:18 UTC, Emskiqq commented
Jenkins retry build

2022-09-16 14:35 UTC, Emskiqq commented
Jenkins retry build

2022-09-19 09:51 UTC, desislava-hristova-ontotext requested changes
Please, removed all changes caused by auto formatting of your IDE and turn off the auto formatting. This makes the MR hard to read. Leave only the relevant to the issue changes.

2022-09-19 09:52 UTC, desislava-hristova-ontotext commented on src/pages/home.html
> +                                <div ng-if="getLicense().licenseCapabilities.length!==0">
Use space between the operator: getLicense().licenseCapabilities.length !== 0.

2022-09-19 09:52 UTC, desislava-hristova-ontotext commented on src/pages/home.html
> +                                <div ng-if="getLicense().licenseCapabilities.length===0">
Wrap the operator with spaces.

2022-09-30 11:34 UTC, Emskiqq commented
Jenkins retry build

2022-09-30 11:45 UTC, desislava-hristova-ontotext commented
Jenkins retry build

2022-09-30 14:35 UTC, Emskiqq commented
Jenkins retry build

2022-09-30 18:03 UTC, desislava-hristova-ontotext approved these changes

2022-09-30 18:04 UTC, merged