GDB-8369 Cluster View broken toast error for lack of user permissions
Ontotext-AD/graphdb-workbench pull request #968
Opened 2023-07-17 15:34 UTC by Emskiqq

GDB-8369 Ascertaining whether the error is a 403 and calls getError(error.data, error.status) if it is

2023-07-17 20:36 UTC, Emskiqq commented
Jenkins retry build

2023-07-18 04:55 UTC, yordanalexandrov commented on src/js/angular/clustermanagement/controllers.js
> +                    const failedNodesList = error.status === 403 ? getError(error.data, error.status) : Object.keys(error.data)
Is it only 403 that needs to be handled like this?

IMO all errors should be handled with `getError()`, except the one that returns the failed delete from the cluster.

2023-07-18 05:17 UTC, yordanalexandrov commented on src/js/angular/clustermanagement/controllers.js
> +                    const failedNodesList = error.status === 403 ? getError(error.data, error.status) : Object.keys(error.data)
Also change the name of the variable if it might contain different messages

2023-07-18 05:30 UTC, yordanalexandrov commented on src/js/angular/clustermanagement/controllers.js
> +                    const failedNodesList = error.status === 403 ? getError(error.data, error.status) : Object.keys(error.data)
The other actions in this view have this case handled. You can the same aproach here as well, so it is consistent.

2023-07-18 05:32 UTC, yordanalexandrov commented
Also please change the name of the MR as it has nothing to do with what the changes are.

2023-07-18 06:21 UTC, yordanalexandrov requested changes

2023-07-18 06:21 UTC, yordanalexandrov commented on src/js/angular/clustermanagement/controllers.js
> +                    const failedNodesList = error.status === 403 ? getError(error.data, error.status) : Object.keys(error.data)
The other actions in this view have this case handled. You can the same aproach here as well, so it is consistent.

2023-07-19 06:17 UTC, yordanalexandrov requested changes

2023-07-19 06:17 UTC, yordanalexandrov commented on src/js/angular/clustermanagement/controllers.js
> +                    handleAddRemoveErrors(error.data, error.status, failMessage);
Rename the function to something more generic `handleErrors` perhaps

2023-07-19 10:51 UTC, yordanalexandrov approved these changes

2023-07-19 12:50 UTC, merged